# Generated by Django 4.1.7 on 2023-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bench11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
    ]
