# Generated by Django 4.1.7 on 2023-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bench26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
    ]
