# Generated by Django 4.1.7 on 2023-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_room', '0002_bench26'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bench31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench35',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench41',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench43',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench44',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
        migrations.CreateModel(
            name='Bench45',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
    ]
